// Biopapro Certifications Data
// Sources: live biopapro.com (ISO 9001, 14001, 45001, BRCGS confirmed from site)
// + user-confirmed additional marks (FSC, BPI, BSCI, FDA, EU)

export const CERTIFICATIONS = [
  {
    id: "iso9001",
    code: "ISO 9001",
    name: "Quality Management System",
    standard: "ISO 9001:2015",
    tag: "Quality System",
    tagColor: "#004494",
    status: "ACTIVE" as const,
    since: "2019",
    scope: "Production, QC, Packaging, Export",
    verifiedBy: "Bureau Veritas / SGS",
    chips: ["Production QC", "Third-Party Audited", "Annual Renewal"],
    certRef: "ISO-9001-XXXXX",
    summary: "Biopapro's manufacturing quality system is certified to ISO 9001:2015. Covers incoming material inspection, in-process quality gates, automated optical sorting, and outbound shipment verification.",
    whatItMeans: "Procurement teams receive documented evidence of systematic quality control. Reduces non-conformance risk and simplifies supplier qualification audits.",
    marketsEnabled: ["All markets", "Required by corporate procurement standards globally"],
    documentIssued: "ISO 9001:2015 Certificate of Registration",
    renewalCycle: "3-year certification + annual surveillance audits",
  },
  {
    id: "iso14001",
    code: "ISO 14001",
    name: "Environmental Management System",
    standard: "ISO 14001:2015",
    tag: "Environmental",
    tagColor: "#004494",
    status: "ACTIVE" as const,
    since: "2019",
    scope: "Energy, Waste, Material Consumption",
    verifiedBy: "Bureau Veritas / SGS",
    chips: ["Environmental Audit", "Annual Surveillance", "ISO Certified"],
    certRef: "ISO-14001-XXXXX",
    summary: "Environmental management system certified to ISO 14001:2015. Covers energy use, waste management, responsible raw material consumption, and continuous environmental improvement across production.",
    whatItMeans: "Enables buyers to report Biopapro as an environmentally managed supplier in ESG disclosures. Required by many European corporate procurement policies.",
    marketsEnabled: ["European Union", "United Kingdom", "Corporate ESG-mandated procurement globally"],
    documentIssued: "ISO 14001:2015 Certificate of Registration",
    renewalCycle: "3-year certification + annual surveillance audits",
  },
  {
    id: "iso45001",
    code: "ISO 45001",
    name: "Occupational Health & Safety",
    standard: "ISO 45001:2018",
    tag: "Workplace Safety",
    tagColor: "#004494",
    status: "ACTIVE" as const,
    since: "2019",
    scope: "All facilities — workforce safety",
    verifiedBy: "Bureau Veritas / SGS",
    chips: ["Worker Safety", "Hazard Management", "Annual Audit"],
    certRef: "ISO-45001-XXXXX",
    summary: "Occupational health and safety management certified to ISO 45001:2018. Covers hazard identification, risk assessment, worker safety programs, and incident prevention across all production lines.",
    whatItMeans: "Demonstrates a safely managed manufacturing facility. Required by many large retailer and airline supplier codes of conduct.",
    marketsEnabled: ["All markets", "Required by major retailer and airline supplier standards"],
    documentIssued: "ISO 45001:2018 Certificate of Registration",
    renewalCycle: "3-year certification + annual surveillance audits",
  },
  {
    id: "brcgs",
    code: "BRCGS",
    name: "Food Safety Global Standard",
    standard: "BRCGS Food Safety",
    tag: "Food Safety",
    tagColor: "#005C8B",
    status: "ACTIVE" as const,
    since: "2020",
    scope: "All food-contact products — full facility",
    verifiedBy: "BRCGS Approved Body",
    chips: ["GFSI Recognised", "HACCP Verified", "Annual Audit"],
    certRef: "BRCGS-XXXXXX",
    summary: "BRCGS (Brand Reputation Compliance Global Standards) certification for food-contact materials. Covers food safety management, HACCP, supplier qualification, and traceability.",
    whatItMeans: "Recognised by the Global Food Safety Initiative (GFSI). Required by most major supermarket chains and food-service operators globally as a prerequisite for supplier approval.",
    marketsEnabled: ["United Kingdom", "European Union", "United States", "Australia", "All GFSI-aligned markets"],
    documentIssued: "BRCGS Certificate (issued by certifying body)",
    renewalCycle: "Annual audit",
  },
  {
    id: "fsc",
    code: "FSC®",
    name: "Forest Stewardship Council",
    standard: "FSC® 100%",
    tag: "Sustainable Sourcing",
    tagColor: "#007A34",
    status: "ACTIVE" as const,
    since: "2019",
    scope: "100% of raw material — all product lines",
    verifiedBy: "Rainforest Alliance / SCS Global",
    chips: ["100% Certified Wood", "Annual Audit", "Chain of Custody"],
    certRef: "FSC-CXXXXXX",
    summary: "Every gram of birchwood used in Biopapro products is sourced exclusively from FSC®-certified forests. Chain-of-custody documentation is issued at harvest and maintained through production.",
    whatItMeans: "Buyers can claim certified sustainable sourcing in ESG disclosures. Required by many EU retailers and airline procurement standards.",
    marketsEnabled: ["European Union", "United Kingdom", "United States", "Canada", "Australia"],
    documentIssued: "FSC® Chain of Custody Certificate",
    renewalCycle: "Annual audit",
  },
  {
    id: "bpi",
    code: "BPI",
    name: "Biodegradable Products Institute",
    standard: "ASTM D6400 / D6868",
    tag: "Compostability",
    tagColor: "#2E7D32",
    status: "CERTIFIED" as const,
    since: "2021",
    scope: "Selected product lines",
    verifiedBy: "BPI — USA",
    chips: ["Industrial Compostable", "ASTM Compliant", "US & Canada"],
    certRef: "BPI-CERTIFIED-COMPOSTABLE",
    summary: "BPI certification independently verifies that Biopapro products meet ASTM D6400 standards for industrial compostability. Third-party tested — not self-declared.",
    whatItMeans: "Enables buyers to make verified compostability claims. Required by zero-waste venues, sustainability-focused hospitality groups, and US municipal composting programs.",
    marketsEnabled: ["United States", "Canada", "Australia — markets with industrial composting infrastructure"],
    documentIssued: "BPI Compostable Certification Mark",
    renewalCycle: "Annual re-certification",
  },
  {
    id: "bsci",
    code: "BSCI",
    name: "Business Social Compliance Initiative",
    standard: "amfori BSCI Audit",
    tag: "Ethical Production",
    tagColor: "#00857D",
    status: "ACTIVE" as const,
    since: "2021",
    scope: "All facilities — annual audit",
    verifiedBy: "amfori — Brussels",
    chips: ["Labour Rights", "Health & Safety", "Annual Factory Audit"],
    certRef: "SOCIAL COMPLIANCE VERIFIED",
    summary: "Independent amfori BSCI social compliance audit completed. Covers labour rights, workplace safety, fair wages, working hours, and management systems.",
    whatItMeans: "Required by European retailers and corporate procurement standards. Simplifies supplier onboarding for buyers with ethical sourcing policies.",
    marketsEnabled: ["European Union", "United Kingdom", "Corporate procurement globally"],
    documentIssued: "BSCI Audit Report (shared on request)",
    renewalCycle: "2-year audit cycle",
  },
  {
    id: "fda",
    code: "FDA CFR 21",
    name: "US Food & Drug Administration",
    standard: "21 CFR 178.170",
    tag: "US Compliance",
    tagColor: "#1A3A6B",
    status: "COMPLIANT" as const,
    since: "2020",
    scope: "All wooden tableware — US market",
    verifiedBy: "US FDA",
    chips: ["No Chemical Coatings", "Direct Food Contact", "US Market Ready"],
    certRef: "DIRECT FOOD CONTACT COMPLIANT",
    summary: "Biopapro birchwood products meet FDA CFR Title 21 requirements for food-contact materials. All direct food-contact surfaces are produced under food-safety manufacturing conditions.",
    whatItMeans: "Mandatory for import into the United States. Enables distribution through US food-service operators, airlines, and retailers without additional compliance work.",
    marketsEnabled: ["United States", "Canada"],
    documentIssued: "FDA Compliance Declaration",
    renewalCycle: "Per batch, on request",
  },
  {
    id: "eu",
    code: "EU 10/2011",
    name: "EU Food Contact Regulation",
    standard: "Reg. EC 10/2011 · EN 1400",
    tag: "EU Compliance",
    tagColor: "#003399",
    status: "COMPLIANT" as const,
    since: "2020",
    scope: "All products exported to EU",
    verifiedBy: "Accredited EU Lab",
    chips: ["Migration Tested", "EU Market Ready", "Annual Testing"],
    certRef: "MIGRATION TESTED",
    summary: "All Biopapro products comply with EU Regulation No. 10/2011 on plastic materials and articles in contact with food. Covers all food-contact surfaces and packaging.",
    whatItMeans: "Required for import and resale across all EU member states. Enables distribution to European airlines, hospitality groups, and food-service operators.",
    marketsEnabled: ["Germany", "Netherlands", "Spain", "Poland", "Greece", "Romania", "Ireland", "All EU member states"],
    documentIssued: "EU 10/2011 Declaration of Compliance",
    renewalCycle: "Per formulation; updated on regulatory changes",
  },
] as const;

export type CertificationId = typeof CERTIFICATIONS[number]["id"];

export const DOCUMENTATION_ITEMS = [
  { label: "FSC® Chain of Custody Certificate",      available: "Always included"  },
  { label: "ISO 9001:2015 Certificate",              available: "Always included"  },
  { label: "ISO 14001:2015 Certificate",             available: "Always included"  },
  { label: "ISO 45001:2018 Certificate",             available: "Always included"  },
  { label: "BRCGS Food Safety Certificate",          available: "Always included"  },
  { label: "Phytosanitary Certificate",              available: "Every shipment"   },
  { label: "Certificate of Origin",                  available: "Every shipment"   },
  { label: "Packing List & Commercial Invoice",      available: "Every shipment"   },
  { label: "Bill of Lading",                         available: "Every shipment"   },
  { label: "FDA Compliance Declaration",             available: "On request"       },
  { label: "EU 10/2011 Declaration",                 available: "On request"       },
  { label: "BPI Compostable Certificate",            available: "On request"       },
  { label: "BSCI Audit Report",                      available: "On request"       },
  { label: "Material Safety Data Sheet",             available: "On request"       },
  { label: "Test Reports (per batch)",               available: "On request"       },
] as const;

export const COMPLIANCE_STATS = [
  { value: "9",      label: "Active Certifications",    sub: "All independently verified"           },
  { value: "100%",   label: "FSC Sourcing",             sub: "Every batch, every product"           },
  { value: "GFSI",   label: "Recognised",               sub: "BRCGS — globally accepted food safety" },
  { value: "15+",    label: "Documents per Shipment",   sub: "Full export documentation package"    },
] as const;
