// Biopapro Certifications Data
// Source: real certificates on file (Biopapro Cutleries Pvt. Ltd. / BCPL), verified
// against the issued PDFs — not self-declared. Only certifications with a document
// on file are listed here; nothing is shown without a backing certificate.

export const CERTIFICATIONS = [
  {
    id: "iso9001",
    code: "ISO 9001",
    name: "Quality Management System",
    standard: "ISO 9001:2015",
    tag: "Quality System",
    tagColor: "#004494",
    status: "ACTIVE" as const,
    since: "2025",
    scope: "Manufacture and export of disposable wooden cutlery (spoons, forks, knives, scoops, sporks, tea/coffee stirrers, skewers) and paper straws",
    verifiedBy: "ICV Assessments Pvt. Ltd.",
    chips: ["IAF Member Scheme", "EGAC Accredited", "Expires Dec 2028"],
    certRef: "IN/87521966/2521",
    summary: "Biopapro's manufacturing quality system is certified to ISO 9001:2015 by ICV Assessments, an EGAC-accredited certification body. Issued 12 Dec 2025, valid to 11 Dec 2028, with surveillance audits due in Nov 2026 and Nov 2027.",
    whatItMeans: "Procurement teams receive documented, third-party-audited evidence of a managed quality system — not a self-declared claim.",
    marketsEnabled: ["All markets", "Supports corporate procurement supplier-qualification requirements"],
    documentIssued: "ISO 9001:2015 Certificate of Registration",
    renewalCycle: "Valid to 11 Dec 2028, with surveillance audits in Nov 2026 and Nov 2027",
  },
  {
    id: "iso14001",
    code: "ISO 14001",
    name: "Environmental Management System",
    standard: "ISO 14001:2015",
    tag: "Environmental",
    tagColor: "#004494",
    status: "ACTIVE" as const,
    since: "2025",
    scope: "Manufacture and export of disposable wooden cutlery (spoons, forks, knives, scoops, sporks, tea/coffee stirrers, skewers) and paper straws",
    verifiedBy: "ICV Assessments Pvt. Ltd.",
    chips: ["IAF Member Scheme", "EGAC Accredited", "Expires Dec 2028"],
    certRef: "IN/78621967/8965",
    summary: "Environmental management system certified to ISO 14001:2015 by ICV Assessments. Issued 12 Dec 2025, valid to 11 Dec 2028, with surveillance audits due in Nov 2026 and Nov 2027.",
    whatItMeans: "Documents a managed approach to energy, waste, and material use across production — independently audited, not self-reported.",
    marketsEnabled: ["All markets", "Supports ESG supplier-disclosure requests"],
    documentIssued: "ISO 14001:2015 Certificate of Registration",
    renewalCycle: "Valid to 11 Dec 2028, with surveillance audits in Nov 2026 and Nov 2027",
  },
  {
    id: "iso45001",
    code: "ISO 45001",
    name: "Occupational Health & Safety",
    standard: "ISO 45001:2018",
    tag: "Workplace Safety",
    tagColor: "#004494",
    status: "ACTIVE" as const,
    since: "2025",
    scope: "Manufacture and export of disposable wooden cutlery (spoons, forks, knives, scoops, sporks, tea/coffee stirrers, skewers) and paper straws",
    verifiedBy: "ICV Assessments Pvt. Ltd.",
    chips: ["IAF Member Scheme", "EGAC Accredited", "Expires Dec 2028"],
    certRef: "IN/38421968/7610",
    summary: "Occupational health and safety management certified to ISO 45001:2018 by ICV Assessments. Issued 12 Dec 2025, valid to 11 Dec 2028, with surveillance audits due in Nov 2026 and Nov 2027.",
    whatItMeans: "Independently audited evidence of a managed workplace-safety system across the factory floor.",
    marketsEnabled: ["All markets", "Supports supplier code-of-conduct reviews"],
    documentIssued: "ISO 45001:2018 Certificate of Registration",
    renewalCycle: "Valid to 11 Dec 2028, with surveillance audits in Nov 2026 and Nov 2027",
  },
  {
    id: "brcgs",
    code: "BRCGS",
    name: "Global Standard for Consumer Products",
    standard: "BRCGS Consumer Products — General Merchandise, Issue 4",
    tag: "Product Standard",
    tagColor: "#005C8B",
    status: "ACTIVE" as const,
    since: "2026",
    scope: "Manufacture of wooden cutlery by wood soaking, pressing, and heat-forming, packed in carton boxes. Excludes skewers, paper straws, and printing processes.",
    verifiedBy: "SGS United Kingdom Ltd.",
    chips: ["Foundation Level", "Grade: PASSED", "UKAS Accredited"],
    certRef: "IN21/818844913",
    summary: "Certified to the BRCGS Global Standard for Consumer Products — General Merchandise (Issue 4), Foundation Level, audited by SGS United Kingdom. Evaluated 17 Jul 2026, certificate issued 1 Sep 2026, valid to 22 Aug 2027.",
    whatItMeans: "A UKAS-accredited, third-party-audited product standard — supports retailer and food-service supplier onboarding.",
    marketsEnabled: ["United Kingdom", "European Union", "Markets requiring BRCGS-audited suppliers"],
    documentIssued: "BRCGS Certificate of Registration",
    renewalCycle: "Re-evaluation due 11 Jul 2027, certificate expires 22 Aug 2027",
  },
  {
    id: "fsc",
    code: "FSC®",
    name: "Forest Stewardship Council — Chain of Custody",
    standard: "FSC-STD-40-004 V3-1 (Chain of Custody)",
    tag: "Sustainable Sourcing",
    tagColor: "#007A34",
    status: "ACTIVE" as const,
    since: "2022",
    scope: "Purchase of FSC 100% semi-finished wooden cutlery (spoons, forks, knives, stirrers, flats); manufacturing and sale of FSC 100% wooden cutlery using the transfer system",
    verifiedBy: "SGS Hong Kong Limited",
    chips: ["FSC 100%", "Chain of Custody", "Certified Since Jan 2022"],
    certRef: "SGSHK-COC-400230",
    summary: "Biopapro's wooden cutlery supply chain is FSC® Chain-of-Custody certified by SGS Hong Kong, using the transfer system. Certified since 19 Jan 2022; current certificate valid 9 Feb 2023 to 18 Jan 2027, subject to satisfactory surveillance audits.",
    whatItMeans: "Verifies the FSC 100% claim on wooden cutlery through the supply chain — checked annually, not a one-time declaration.",
    marketsEnabled: ["European Union", "United Kingdom", "United States", "Markets requiring FSC-sourced material"],
    documentIssued: "FSC® Chain of Custody Certificate",
    renewalCycle: "Valid to 18 Jan 2027, subject to satisfactory surveillance audits",
  },
] as const;

export type CertificationId = typeof CERTIFICATIONS[number]["id"];

export const DOCUMENTATION_ITEMS = [
  { label: "Certificate of Origin",                          available: "Every shipment"   },
  { label: "Packing List & Commercial Invoice",               available: "Every shipment"   },
  { label: "Bill of Lading",                                  available: "Every shipment"   },
  { label: "FSC® Chain of Custody Certificate",                available: "Always included"  },
  { label: "ISO 9001:2015 Certificate",                       available: "Always included"  },
  { label: "ISO 14001:2015 Certificate",                      available: "Always included"  },
  { label: "ISO 45001:2018 Certificate",                      available: "Always included"  },
  { label: "BRCGS Certificate of Registration",               available: "Always included"  },
  { label: "Heavy Metal & Phthalate Test Report (SGS)",        available: "On request"       },
  { label: "Microbiology Test Report (Intertek)",              available: "On request"       },
  { label: "Packaging Material Test Report — PFAS/Fluorine (Intertek)", available: "On request" },
  { label: "Material Safety Data Sheet (Adhesive)",            available: "On request"       },
  { label: "Test Reports (per batch)",                        available: "On request"       },
] as const;

export const COMPLIANCE_STATS = [
  { value: "5",      label: "Active Certifications",    sub: "All independently verified"           },
  { value: "100%",   label: "FSC Sourcing",             sub: "Chain-of-custody verified"            },
  { value: "UKAS",   label: "BRCGS Accredited",         sub: "Audited by SGS United Kingdom"        },
  { value: "3",      label: "Independent Test Reports", sub: "SGS & Intertek, on request"           },
] as const;
